version: '3'
services:
  mongo:
    image: mongo:4.4.2
    volumes:
      - mongo-data:/data/db
    expose:
      - "27017"
  app:
    image: rodrigodz/brito
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    env_file: .env
    ports:
      - "3333:3333"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
volumes:
  mongo-data: